### PR TITLE
Fix Build error

### LINKED ISSUE #613: Build Error
Steps to reproduce: 
- `npm run build` throws error
image

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #613

### CODE REVIEW

File: src/devhub/entity/post/History.jsx [hunk 1]
```diff
@@ -7,22 +7,7 @@ props.timestamp: number;
 props.referral: any;
 */
 
-function href(widgetName, linkProps) {
```
Comment (elliotBraem) [inline src/devhub/entity/post/History.jsx:10]: With this replacement, did you double check that the function call is adjusted? This href function is slightly different from the VM.require href

Comment (Megha-Dev-19) [reply src/devhub/entity/post/History.jsx:10]: I didn't since the code was from common.jsx, I expected it to be similar to href of VM
I will take a look

Comment (Megha-Dev-19) [reply src/devhub/entity/post/History.jsx:10]: Fixed it, it works now
